language: java

jdk:
   - oraclejdk8

before_script:
   -pip install --user codecov

script:
   - mvn clean checkstyle:checkstyle findbugs:findbugs install
   - cd benchmark
   - mvn clean compile

after_success:
   -  codecov
