language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn dependency:go-offline
  - mvn clean install -Dmaven.compiler.source=1.6 -Dmaven.compiler.target=1.6

after_success:
  - bash <(curl -s https://codecov.io/bash)
